<?php

namespace AppBundle\Repository;

/**
 * AssocProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssocProductRepository extends \Doctrine\ORM\EntityRepository
{
}
