<?php

namespace AppBundle\Repository;

/**
 * HikashopTaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HikashopTaxRepository extends \Doctrine\ORM\EntityRepository
{
}
