<?php

namespace AppBundle\Repository;

/**
 * HikashopProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HikashopProductRepository extends \Doctrine\ORM\EntityRepository
{
}
