<?php

namespace AppBundle\Repository;

/**
 * HikashopCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HikashopCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
