<?php

namespace AppBundle\Repository;

/**
 * HikashopProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HikashopProductCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
