<?php

namespace AppBundle\Repository;

/**
 * OrderLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderLineRepository extends \Doctrine\ORM\EntityRepository
{
}
