<?php

namespace AppBundle\Repository;

/**
 * OrderHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
