<?php

namespace HikashopBundle\Repository;

/**
 * HikashopPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HikashopPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
