<?php

namespace HikashopBundle\Repository;

/**
 * HikashopOrderProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HikashopOrderProductRepository extends \Doctrine\ORM\EntityRepository
{
}
