<?php

namespace HikashopBundle\Repository;

/**
 * HikashopFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HikashopFileRepository extends \Doctrine\ORM\EntityRepository
{
}
