<?php

namespace HikashopBundle\Repository;

/**
 * HikashopAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HikashopAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
