<?php

namespace HikashopBundle\Repository;

/**
 * HikashopOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HikashopOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
