# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_users:
            entity: { class: AppBundle\Entity\User, property: email }
    role_hierarchy:
        ROLE_SUPERADMIN: [ROLE_LIBRAIRE, ROLE_APPROBATOR, ROLE_ALLOWED_TO_SWITCH]
        ROLE_LIBRAIRE: [ROLE_USER]
        ROLE_APPROBATOR: [ROLE_USER]
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path: /logout
                target: /
            switch_user: ~

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_LIBRAIRE }