# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
    app.command.test:
        class: AppBundle\Command\TestCommand
        arguments: ["@doctrine.orm.entity_manager", "@logger"]
        autowire: true
        public: true
        tags:
            - { name: console.command }
    app.command.get_orders:
        class: AppBundle\Command\GetOrdersCommand
        arguments: ["@doctrine.orm.entity_manager", "@logger", "@mailer"]
        autowire: true
        public: true
        tags:
            - { name: console.command }
    app.command.sync_products:
        class: AppBundle\Command\SyncProductsCommand
        arguments: ["@doctrine.orm.entity_manager", "@logger", "@mailer"]
        autowire: true
        public: true
        tags:
            - { name: console.command }

